export const FILMS_REQUEST = 'FILMS_REQUEST'
export const LOAD_FILMS_SUCCESS = 'LOAD_FILMS_SUCCESS'
export const FILMS_FAILURE = 'FILMS_FAILURE'
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
